module.exports = [
  {
    id: "usr-admin-1",
    email: "admin@qcasa.uy",
    password: "admin123",
    role: "admin",
    name: "Administrador QPROPIEDADES",
    phone: "095789647",
  },
  {
    id: "usr-owner-1",
    email: "alejandro.gomez@qcasa.demo",
    password: "prop123",
    role: "owner",
    name: "Alejandro Gómez",
    phone: "095789647",
  },
  {
    id: "usr-owner-2",
    email: "mariana.pereira@qcasa.demo",
    password: "prop123",
    role: "owner",
    name: "Mariana Pereira",
    phone: "095789647",
  },
  {
    id: "usr-owner-3",
    email: "carlos.fernandez@qcasa.demo",
    password: "prop123",
    role: "owner",
    name: "Carlos Fernández",
    phone: "095789647",
  },
  {
    id: "usr-owner-4",
    email: "lucia.rodriguez@qcasa.demo",
    password: "prop123",
    role: "owner",
    name: "Lucía Rodríguez",
    phone: "095789647",
  },
  {
    id: "usr-owner-5",
    email: "gabriel.martinez@qcasa.demo",
    password: "prop123",
    role: "owner",
    name: "Gabriel Martínez",
    phone: "095789647",
  },
];
